#Build: docker-compose build
#Iniciar: docker-compose up -d (Cria e roda todos os containers)
#Parar: docker-compose stop

# Versão do Docker Compose
version: "3.9"
# Serviços que serão executados pelo docker-compose
services:
    # Este será o nome do servidor de banco de dados
    DockerDb:
        # Imagem que estará usando, neste caso, a versão 2019 do Sql Server mais recente
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        # Variáveis de ambiente
        environment:
            # Sua senha do banco de dados
            SA_PASSWORD: "Legoshi@123"
            # Com o valor "Y", expressa que possui licença válida do Sql Server instalada
            ACCEPT_EULA: "Y"
    # API
    webapi:
        # Apontando para o nome da pasta que contem o arquivo Dockerfile
        build: ./WebApi.Docker.Backend/
        # Definição da porta que a api utilizará
        ports:
            - "8000:80"
        # Referenciar o nome do serviço que a API será dependente, no caso o DockerDb (linha 4)
        depends_on:
            - DockerDb